services:
  lyndrix:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lyndrix-core-dev
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app # Code Mount f√ºr Hot-Reload
      #      - ./app/plugins:/app/plugins # Plugins direkt editieren
      - ./.dev/secure_data:/data/security
    environment:
      - DATABASE_URL=mysql+pymysql://admin:secret@db/lyndrix_db
      - PYTHONUNBUFFERED=1
      - LYNDRIX_MASTER_KEY=C2RNVbITSzb60iA1LDowLwBuIXehvDPRzfV6FCfH
      - ENV_TYPE=dev
    env_file: ./app/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload --reload-exclude "*.db"
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_started

  db:
    image: mariadb:10.11
    container_name: lyndrix-db-dev
    env_file: ./app/.env
    volumes:
      - ./.dev/db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-uadmin",
          "-psecret",
        ]
      interval: 5s
      timeout: 2s
      retries: 5

  vault:
    image: hashicorp/vault:latest
    container_name: lyndrix-vault-dev
    hostname: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}, "ui": true}'
      VAULT_API_ADDR: "http://vault:8200"
    volumes:
      - ./.dev/vault_data:/vault/file
    command: server
